# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.5.x version
  - 5.5

sudo : true

script: phpunit --bootstrap TicketCorrelator.php TicketCorrelatorTest

deploy:
   edge: true
   provider: cloudfoundry
   gem : travis
   username: go2suresh1979@gmail.com
   password: Live4jesus!
   api: https://api.run.pivotal.io
   organization: VerizonIndia
   space: development
